<script lang="ts">
	import { onMount } from 'svelte';
	import Icon from '@iconify/svelte';
	import { config } from '$lib/config';
	import GameRail from '$lib/components/GameRail.svelte';
	import { games } from '$lib/data/games';
	import { getCDNImageUrl } from '$lib/utils/cdn';

	let userGames: any[] = [];
	let isLoading = true;
	let error = '';

	$: mappedGames = games.map((g) => ({
		...g,
		image: getCDNImageUrl(g.image)
	}));

	async function fetchGallery() {
		try {
			// This fetching will happen on the client-side for now,
			// calling an API that reads registry.json from OCI.
			const res = await fetch('/api/ai/gallery');
			const data = await res.json();
			if (!res.ok) throw new Error(data.error || 'Failed to fetch gallery');
			userGames = data.games || [];
		} catch (err: any) {
			error = err.message;
		} finally {
			isLoading = false;
		}
	}

	onMount(() => {
		window.scrollTo(0, 0);
		fetchGallery();
	});
</script>

<svelte:head>
	<title>{config.branding.name} - AI Community Gallery</title>
</svelte:head>

<div class="font-sans min-h-screen bg-base-200 p-4 text-base-content">
	<div class="mx-auto grid max-w-[1800px] grid-cols-1 gap-6 lg:grid-cols-[1fr_5fr_2fr]">
		<!-- Left Rail -->
		<aside class="hidden h-full lg:block">
			<GameRail games={mappedGames} />
		</aside>

		<!-- Main Content -->
		<main class="flex flex-col gap-6">
			<div
				class="flex flex-col items-center justify-between gap-4 rounded-3xl bg-base-100 p-8 shadow-xl md:flex-row"
			>
				<div class="flex items-center gap-4">
					<div
						class="flex h-16 w-16 items-center justify-center rounded-2xl bg-accent text-base-content shadow-lg"
					>
						<Icon icon="mdi:view-gallery" class="text-4xl" />
					</div>
					<div>
						<h1 class="text-3xl font-black tracking-tight">AI Community Gallery</h1>
						<p class="opacity-70">Play and review games created by the community.</p>
					</div>
				</div>
				<a href="/ai" class="btn btn-primary rounded-2xl font-black text-white">
					<Icon icon="mdi:creation" />
					Create Your Own
				</a>
			</div>

			<div class="min-h-[400px] rounded-3xl bg-base-100 p-6 shadow-xl">
				{#if isLoading}
					<div class="flex h-64 flex-col items-center justify-center gap-4 opacity-50">
						<Icon icon="line-md:loading-alt-loop" class="text-6xl" />
						<p class="font-bold">Loading community magic...</p>
					</div>
				{:else if error}
					<div class="alert alert-error rounded-2xl">
						<Icon icon="mdi:alert-circle" />
						<span>{error}</span>
					</div>
				{:else if userGames.length === 0}
					<div class="flex h-64 flex-col items-center justify-center gap-4 text-center opacity-30">
						<Icon icon="mdi:controller-off" class="text-8xl" />
						<h3 class="text-2xl font-black">No AI games yet!</h3>
						<p>Be the first to create one in the Lab.</p>
					</div>
				{:else}
					<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
						{#each userGames as game}
							<a
								href="/ai/user-g/{game.id}"
								class="group flex flex-col overflow-hidden rounded-2xl border border-neutral/10 transition-all hover:scale-[1.02] hover:border-primary/30 hover:shadow-2xl"
							>
								<div class="relative aspect-video w-full bg-black">
									<div class="absolute inset-0 flex items-center justify-center bg-primary/10">
										<Icon
											icon="mdi:robot"
											class="text-6xl text-primary/40 transition-transform group-hover:scale-110"
										/>
									</div>
									{#if game.sourceGameId}
										<div class="badge badge-accent absolute right-2 top-2 font-bold shadow-md">
											REMIX
										</div>
									{/if}
								</div>
								<div class="flex flex-col p-4">
									<h3 class="truncate text-xl font-black">{game.title}</h3>
									<p class="mt-1 line-clamp-2 h-10 text-sm opacity-60">{game.description}</p>
									<div
										class="mt-4 flex items-center justify-between border-t border-neutral/5 pt-4"
									>
										<div class="flex items-center gap-1 text-primary">
											<Icon icon="mdi:star" />
											<span class="font-bold">{game.avgRating || 'New'}</span>
										</div>
										<span class="text-xs opacity-40"
											>{new Date(game.createdAt).toLocaleDateString()}</span
										>
									</div>
								</div>
							</a>
						{/each}
					</div>
				{/if}
			</div>
		</main>

		<!-- Right Column -->
		<aside class="flex flex-col gap-6">
			<div class="rounded-3xl bg-base-100 p-6 shadow-xl">
				<h3 class="mb-4 text-xl font-black">Join the Craze</h3>
				<p class="text-sm opacity-70">
					Millions of games are being generated by AI. Try remixing popular ones to add your own
					twist!
				</p>
			</div>
		</aside>
	</div>
</div>
